// <auto-generated />
using System;
using CareSynq.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareSynq.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareSynq.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentDate = new DateTime(2025, 11, 24, 11, 58, 50, 995, DateTimeKind.Local).AddTicks(4447),
                            ClinicianId = 1,
                            CreatedDate = new DateTime(2025, 11, 17, 11, 58, 50, 995, DateTimeKind.Local).AddTicks(4477),
                            Notes = "Regular checkup for pressure ulcer prevention",
                            PatientId = 1,
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("CareSynq.Models.Clinician", b =>
                {
                    b.Property<int>("ClinicianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicianId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClinicianId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clinicians");

                    b.HasData(
                        new
                        {
                            ClinicianId = 1,
                            CreatedDate = new DateTime(2025, 11, 17, 11, 58, 50, 995, DateTimeKind.Local).AddTicks(4349),
                            Email = "clinician@test.com",
                            FirstName = "Paul",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "hashedpassword123",
                            PhoneNumber = "5551234567",
                            Specialization = "Wound Care Specialist"
                        });
                });

            modelBuilder.Entity("CareSynq.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("ClinicianId")
                        .HasColumnType("int");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SensorDataId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SensorDataId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("CareSynq.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            CreatedDate = new DateTime(2025, 11, 17, 11, 58, 50, 995, DateTimeKind.Local).AddTicks(4058),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "patient@test.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Khan",
                            PasswordHash = "hashedpassword123",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            PatientId = 2,
                            CreatedDate = new DateTime(2025, 11, 17, 11, 58, 50, 995, DateTimeKind.Local).AddTicks(4063),
                            DateOfBirth = new DateTime(1970, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.green@test.com",
                            FirstName = "Michael",
                            IsActive = false,
                            LastName = "Green",
                            PasswordHash = "hashedpassword123",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("CareSynq.Models.SensorData", b =>
                {
                    b.Property<int>("SensorDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorDataId"));

                    b.Property<double>("ContactAreaPercentage")
                        .HasColumnType("float");

                    b.Property<bool>("IsHighPressureAlert")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<double>("PeakPressureIndex")
                        .HasColumnType("float");

                    b.Property<string>("PressureMapData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SensorMachineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("SensorDataId");

                    b.HasIndex("PatientId");

                    b.HasIndex("SensorMachineId");

                    b.ToTable("SensorDataRecords");
                });

            modelBuilder.Entity("CareSynq.Models.SensorMachine", b =>
                {
                    b.Property<int>("SensorMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorMachineId"));

                    b.Property<int?>("AssignedPatientId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCalibrationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SensorMachineId");

                    b.HasIndex("AssignedPatientId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("SensorMachines");

                    b.HasData(
                        new
                        {
                            SensorMachineId = 1,
                            AssignedPatientId = 1,
                            IsActive = true,
                            LastCalibrationDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelName = "Sensore Mat Pro",
                            SerialNumber = "SM-2024-001"
                        },
                        new
                        {
                            SensorMachineId = 2,
                            AssignedPatientId = 2,
                            IsActive = true,
                            LastCalibrationDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ManufactureDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModelName = "Sensore Mat Pro",
                            SerialNumber = "SM-2024-002"
                        });
                });

            modelBuilder.Entity("CareSynq.Models.Appointment", b =>
                {
                    b.HasOne("CareSynq.Models.Clinician", "Clinician")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareSynq.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareSynq.Models.Comment", b =>
                {
                    b.HasOne("CareSynq.Models.Clinician", "Clinician")
                        .WithMany("Comments")
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CareSynq.Models.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId");

                    b.HasOne("CareSynq.Models.Patient", "Patient")
                        .WithMany("Comments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CareSynq.Models.SensorData", "SensorData")
                        .WithMany("Comments")
                        .HasForeignKey("SensorDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("ParentComment");

                    b.Navigation("Patient");

                    b.Navigation("SensorData");
                });

            modelBuilder.Entity("CareSynq.Models.SensorData", b =>
                {
                    b.HasOne("CareSynq.Models.Patient", "Patient")
                        .WithMany("SensorDataRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CareSynq.Models.SensorMachine", "SensorMachine")
                        .WithMany("SensorDataRecords")
                        .HasForeignKey("SensorMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("SensorMachine");
                });

            modelBuilder.Entity("CareSynq.Models.SensorMachine", b =>
                {
                    b.HasOne("CareSynq.Models.Patient", "AssignedPatient")
                        .WithMany()
                        .HasForeignKey("AssignedPatientId");

                    b.Navigation("AssignedPatient");
                });

            modelBuilder.Entity("CareSynq.Models.Clinician", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CareSynq.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Comments");

                    b.Navigation("SensorDataRecords");
                });

            modelBuilder.Entity("CareSynq.Models.SensorData", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("CareSynq.Models.SensorMachine", b =>
                {
                    b.Navigation("SensorDataRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
